/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SearchRouteImport } from "./routes/search";
import { Route as ReferralsRouteImport } from "./routes/referrals";
import { Route as RecurringIndexRouteImport } from "./routes/recurring/index";
import { Route as JoinRouteImport } from "./routes/join";
import { Route as ProRouteImport } from "./routes/pro";
import { Route as MessagesRouteImport } from "./routes/messages";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as SettingsNotificationsRouteImport } from "./routes/settings/notifications";
import { Route as ProfilePortfolioRouteImport } from "./routes/profile/portfolio";
import { Route as OnboardingArtisanRouteImport } from "./routes/onboarding/artisan";
import { Route as LegalTermsRouteImport } from "./routes/legal/terms";
import { Route as LegalPrivacyRouteImport } from "./routes/legal/privacy";
import { Route as JobsPostRouteImport } from "./routes/jobs/post";
import { Route as ArtisansJobsRouteImport } from "./routes/artisans/jobs";
import { Route as ArtisanEarningsRouteImport } from "./routes/artisan/earnings";
import { Route as ArtisanReviewsRouteImport } from "./routes/artisan/reviews";
import { Route as ArtisanIdRouteImport } from "./routes/artisan.$id";
import { Route as AdminVerificationRouteImport } from "./routes/admin/verification";
import { Route as AdminScoresRouteImport } from "./routes/admin/scores";
import { Route as ArtisansJobsJobIdIndexRouteImport } from "./routes/artisans/jobs/$jobId/index";
import { Route as JobsMineRouteImport } from "./routes/jobs/mine";
import { Route as JobsJobIdBidsRouteImport } from "./routes/jobs/$jobId/bids";
import { Route as BookingsBookingIdRouteImport } from "./routes/bookings/$bookingId";

const SearchRoute = SearchRouteImport.update({
  id: "/search",
  path: "/search",
  getParentRoute: () => rootRouteImport,
} as any);
const ReferralsRoute = ReferralsRouteImport.update({
  id: "/referrals",
  path: "/referrals",
  getParentRoute: () => rootRouteImport,
} as any);
const RecurringIndexRoute = RecurringIndexRouteImport.update({
  id: "/recurring/",
  path: "/recurring/",
  getParentRoute: () => rootRouteImport,
} as any);
const JoinRoute = JoinRouteImport.update({
  id: "/join",
  path: "/join",
  getParentRoute: () => rootRouteImport,
} as any);
const ProRoute = ProRouteImport.update({
  id: "/pro",
  path: "/pro",
  getParentRoute: () => rootRouteImport,
} as any);
const MessagesRoute = MessagesRouteImport.update({
  id: "/messages",
  path: "/messages",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: "/settings/notifications",
  path: "/settings/notifications",
  getParentRoute: () => rootRouteImport,
} as any);
const ProfilePortfolioRoute = ProfilePortfolioRouteImport.update({
  id: "/profile/portfolio",
  path: "/profile/portfolio",
  getParentRoute: () => rootRouteImport,
} as any);
const OnboardingArtisanRoute = OnboardingArtisanRouteImport.update({
  id: "/onboarding/artisan",
  path: "/onboarding/artisan",
  getParentRoute: () => rootRouteImport,
} as any);
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: "/legal/terms",
  path: "/legal/terms",
  getParentRoute: () => rootRouteImport,
} as any);
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: "/legal/privacy",
  path: "/legal/privacy",
  getParentRoute: () => rootRouteImport,
} as any);
const JobsPostRoute = JobsPostRouteImport.update({
  id: "/jobs/post",
  path: "/jobs/post",
  getParentRoute: () => rootRouteImport,
} as any);
const ArtisansJobsRoute = ArtisansJobsRouteImport.update({
  id: "/artisans/jobs",
  path: "/artisans/jobs",
  getParentRoute: () => rootRouteImport,
} as any);
const ArtisanEarningsRoute = ArtisanEarningsRouteImport.update({
  id: "/artisan/earnings",
  path: "/artisan/earnings",
  getParentRoute: () => rootRouteImport,
} as any);
const ArtisanReviewsRoute = ArtisanReviewsRouteImport.update({
  id: "/artisan/reviews",
  path: "/artisan/reviews",
  getParentRoute: () => rootRouteImport,
} as any);
const ArtisanIdRoute = ArtisanIdRouteImport.update({
  id: "/artisan/$id",
  path: "/artisan/$id",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: "/admin/verification",
  path: "/admin/verification",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminScoresRoute = AdminScoresRouteImport.update({
  id: "/admin/scores",
  path: "/admin/scores",
  getParentRoute: () => rootRouteImport,
} as any);
const ArtisansJobsJobIdIndexRoute = ArtisansJobsJobIdIndexRouteImport.update({
  id: "/$jobId/",
  path: "/$jobId/",
  getParentRoute: () => ArtisansJobsRoute,
} as any);
const JobsMineRoute = JobsMineRouteImport.update({
  id: "/jobs/mine",
  path: "/jobs/mine",
  getParentRoute: () => rootRouteImport,
} as any);
const JobsJobIdBidsRoute = JobsJobIdBidsRouteImport.update({
  id: "/jobs/$jobId/bids",
  path: "/jobs/$jobId/bids",
  getParentRoute: () => rootRouteImport,
} as any);
const BookingsBookingIdRoute = BookingsBookingIdRouteImport.update({
  id: "/bookings/$bookingId",
  path: "/bookings/$bookingId",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/join": typeof JoinRoute;
  "/messages": typeof MessagesRoute;
  "/pro": typeof ProRoute;
  "/referrals": typeof ReferralsRoute;
  "/recurring/": typeof RecurringIndexRoute;
  "/search": typeof SearchRoute;
  "/admin/verification": typeof AdminVerificationRoute;
  "/admin/scores": typeof AdminScoresRoute;
  "/artisan/$id": typeof ArtisanIdRoute;
  "/artisan/earnings": typeof ArtisanEarningsRoute;
  "/artisan/reviews": typeof ArtisanReviewsRoute;
  "/artisans/jobs": typeof ArtisansJobsRouteWithChildren;
  "/jobs/post": typeof JobsPostRoute;
  "/legal/privacy": typeof LegalPrivacyRoute;
  "/legal/terms": typeof LegalTermsRoute;
  "/onboarding/artisan": typeof OnboardingArtisanRoute;
  "/profile/portfolio": typeof ProfilePortfolioRoute;
  "/settings/notifications": typeof SettingsNotificationsRoute;
  "/artisans/jobs/$jobId/": typeof ArtisansJobsJobIdIndexRoute;
  "/jobs/mine": typeof JobsMineRoute;
  "/jobs/$jobId/bids": typeof JobsJobIdBidsRoute;
  "/bookings/$bookingId": typeof BookingsBookingIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/join": typeof JoinRoute;
  "/messages": typeof MessagesRoute;
  "/pro": typeof ProRoute;
  "/referrals": typeof ReferralsRoute;
  "/recurring/": typeof RecurringIndexRoute;
  "/search": typeof SearchRoute;
  "/admin/verification": typeof AdminVerificationRoute;
  "/admin/scores": typeof AdminScoresRoute;
  "/artisan/$id": typeof ArtisanIdRoute;
  "/artisan/earnings": typeof ArtisanEarningsRoute;
  "/artisan/reviews": typeof ArtisanReviewsRoute;
  "/artisans/jobs": typeof ArtisansJobsRouteWithChildren;
  "/jobs/post": typeof JobsPostRoute;
  "/legal/privacy": typeof LegalPrivacyRoute;
  "/legal/terms": typeof LegalTermsRoute;
  "/onboarding/artisan": typeof OnboardingArtisanRoute;
  "/profile/portfolio": typeof ProfilePortfolioRoute;
  "/settings/notifications": typeof SettingsNotificationsRoute;
  "/artisans/jobs/$jobId": typeof ArtisansJobsJobIdIndexRoute;
  "/jobs/mine": typeof JobsMineRoute;
  "/jobs/$jobId/bids": typeof JobsJobIdBidsRoute;
  "/bookings/$bookingId": typeof BookingsBookingIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/join": typeof JoinRoute;
  "/messages": typeof MessagesRoute;
  "/pro": typeof ProRoute;
  "/referrals": typeof ReferralsRoute;
  "/recurring/": typeof RecurringIndexRoute;
  "/search": typeof SearchRoute;
  "/admin/verification": typeof AdminVerificationRoute;
  "/admin/scores": typeof AdminScoresRoute;
  "/artisan/$id": typeof ArtisanIdRoute;
  "/artisan/earnings": typeof ArtisanEarningsRoute;
  "/artisan/reviews": typeof ArtisanReviewsRoute;
  "/artisans/jobs": typeof ArtisansJobsRouteWithChildren;
  "/jobs/post": typeof JobsPostRoute;
  "/legal/privacy": typeof LegalPrivacyRoute;
  "/legal/terms": typeof LegalTermsRoute;
  "/onboarding/artisan": typeof OnboardingArtisanRoute;
  "/profile/portfolio": typeof ProfilePortfolioRoute;
  "/settings/notifications": typeof SettingsNotificationsRoute;
  "/artisans/jobs/$jobId/": typeof ArtisansJobsJobIdIndexRoute;
  "/jobs/mine": typeof JobsMineRoute;
  "/jobs/$jobId/bids": typeof JobsJobIdBidsRoute;
  "/bookings/$bookingId": typeof BookingsBookingIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/join"
    | "/messages"
    | "/pro"
    | "/referrals"
    | "/recurring/"
    | "/search"
    | "/admin/verification"
    | "/admin/scores"
    | "/artisan/$id"
    | "/artisan/earnings"
    | "/artisan/reviews"
    | "/artisans/jobs"
    | "/jobs/post"
    | "/jobs/mine"
    | "/jobs/$jobId/bids"
    | "/bookings/$bookingId"
    | "/legal/privacy"
    | "/legal/terms"
    | "/onboarding/artisan"
    | "/profile/portfolio"
    | "/settings/notifications"
    | "/artisans/jobs/$jobId/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/join"
    | "/messages"
    | "/pro"
    | "/referrals"
    | "/recurring/"
    | "/search"
    | "/admin/verification"
    | "/admin/scores"
    | "/artisan/$id"
    | "/artisan/earnings"
    | "/artisan/reviews"
    | "/artisans/jobs"
    | "/jobs/post"
    | "/jobs/mine"
    | "/jobs/$jobId/bids"
    | "/bookings/$bookingId"
    | "/legal/privacy"
    | "/legal/terms"
    | "/onboarding/artisan"
    | "/profile/portfolio"
    | "/settings/notifications"
    | "/artisans/jobs/$jobId";
  id:
    | "__root__"
    | "/"
    | "/join"
    | "/messages"
    | "/pro"
    | "/referrals"
    | "/recurring/"
    | "/search"
    | "/admin/verification"
    | "/admin/scores"
    | "/artisan/$id"
    | "/artisan/earnings"
    | "/artisan/reviews"
    | "/artisans/jobs"
    | "/jobs/post"
    | "/jobs/mine"
    | "/jobs/$jobId/bids"
    | "/bookings/$bookingId"
    | "/legal/privacy"
    | "/legal/terms"
    | "/onboarding/artisan"
    | "/profile/portfolio"
    | "/settings/notifications"
    | "/artisans/jobs/$jobId/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  JoinRoute: typeof JoinRoute;
  MessagesRoute: typeof MessagesRoute;
  ProRoute: typeof ProRoute;
  ReferralsRoute: typeof ReferralsRoute;
  RecurringIndexRoute: typeof RecurringIndexRoute;
  SearchRoute: typeof SearchRoute;
  AdminVerificationRoute: typeof AdminVerificationRoute;
  AdminScoresRoute: typeof AdminScoresRoute;
  ArtisanIdRoute: typeof ArtisanIdRoute;
  ArtisanEarningsRoute: typeof ArtisanEarningsRoute;
  ArtisanReviewsRoute: typeof ArtisanReviewsRoute;
  ArtisansJobsRoute: typeof ArtisansJobsRouteWithChildren;
  JobsPostRoute: typeof JobsPostRoute;
  JobsMineRoute: typeof JobsMineRoute;
  JobsJobIdBidsRoute: typeof JobsJobIdBidsRoute;
  LegalPrivacyRoute: typeof LegalPrivacyRoute;
  LegalTermsRoute: typeof LegalTermsRoute;
  OnboardingArtisanRoute: typeof OnboardingArtisanRoute;
  ProfilePortfolioRoute: typeof ProfilePortfolioRoute;
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute;
  BookingsBookingIdRoute: typeof BookingsBookingIdRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/search": {
      id: "/search";
      path: "/search";
      fullPath: "/search";
      preLoaderRoute: typeof SearchRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/referrals": {
      id: "/referrals";
      path: "/referrals";
      fullPath: "/referrals";
    };
    "/recurring/": {
      id: "/recurring/";
      path: "/recurring/";
      fullPath: "/recurring/";
      preLoaderRoute: typeof ReferralsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/join": {
      id: "/join";
      path: "/join";
      fullPath: "/join";
      preLoaderRoute: typeof JoinRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/pro": {
      id: "/pro";
      path: "/pro";
      fullPath: "/pro";
      preLoaderRoute: typeof ProRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/messages": {
      id: "/messages";
      path: "/messages";
      fullPath: "/messages";
      preLoaderRoute: typeof MessagesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/notifications": {
      id: "/settings/notifications";
      path: "/settings/notifications";
      fullPath: "/settings/notifications";
      preLoaderRoute: typeof SettingsNotificationsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/profile/portfolio": {
      id: "/profile/portfolio";
      path: "/profile/portfolio";
      fullPath: "/profile/portfolio";
      preLoaderRoute: typeof ProfilePortfolioRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/onboarding/artisan": {
      id: "/onboarding/artisan";
      path: "/onboarding/artisan";
      fullPath: "/onboarding/artisan";
      preLoaderRoute: typeof OnboardingArtisanRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/legal/terms": {
      id: "/legal/terms";
      path: "/legal/terms";
      fullPath: "/legal/terms";
      preLoaderRoute: typeof LegalTermsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/legal/privacy": {
      id: "/legal/privacy";
      path: "/legal/privacy";
      fullPath: "/legal/privacy";
      preLoaderRoute: typeof LegalPrivacyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/jobs/post": {
      id: "/jobs/post";
      path: "/jobs/post";
      fullPath: "/jobs/post";
      preLoaderRoute: typeof JobsPostRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/artisans/jobs": {
      id: "/artisans/jobs";
      path: "/artisans/jobs";
      fullPath: "/artisans/jobs";
      preLoaderRoute: typeof ArtisansJobsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/artisan/earnings": {
      id: "/artisan/earnings";
      path: "/artisan/earnings";
      fullPath: "/artisan/earnings";
      preLoaderRoute: typeof ArtisanEarningsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/artisan/reviews": {
      id: "/artisan/reviews";
      path: "/artisan/reviews";
      fullPath: "/artisan/reviews";
      preLoaderRoute: typeof ArtisanReviewsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/artisan/$id": {
      id: "/artisan/$id";
      path: "/artisan/$id";
      fullPath: "/artisan/$id";
      preLoaderRoute: typeof ArtisanIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin/verification": {
      id: "/admin/verification";
      path: "/admin/verification";
      fullPath: "/admin/verification";
      preLoaderRoute: typeof AdminVerificationRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin/scores": {
      id: "/admin/scores";
      path: "/admin/scores";
      fullPath: "/admin/scores";
      preLoaderRoute: typeof AdminScoresRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/artisans/jobs/$jobId/": {
      id: "/artisans/jobs/$jobId/";
      path: "/$jobId";
      fullPath: "/artisans/jobs/$jobId/";
      preLoaderRoute: typeof ArtisansJobsJobIdIndexRouteImport;
      parentRoute: typeof ArtisansJobsRoute;
    };
    "/jobs/mine": {
      id: "/jobs/mine";
      path: "/jobs/mine";
      fullPath: "/jobs/mine";
      preLoaderRoute: typeof JobsMineRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/jobs/$jobId/bids": {
      id: "/jobs/$jobId/bids";
      path: "/jobs/$jobId/bids";
      fullPath: "/jobs/$jobId/bids";
      preLoaderRoute: typeof JobsJobIdBidsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/bookings/$bookingId": {
      id: "/bookings/$bookingId";
      path: "/bookings/$bookingId";
      fullPath: "/bookings/$bookingId";
      preLoaderRoute: typeof BookingsBookingIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface ArtisansJobsRouteChildren {
  ArtisansJobsJobIdIndexRoute: typeof ArtisansJobsJobIdIndexRoute;
}

const ArtisansJobsRouteChildren: ArtisansJobsRouteChildren = {
  ArtisansJobsJobIdIndexRoute: ArtisansJobsJobIdIndexRoute,
};

const ArtisansJobsRouteWithChildren = ArtisansJobsRoute._addFileChildren(ArtisansJobsRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JoinRoute: JoinRoute,
  MessagesRoute: MessagesRoute,
  ProRoute: ProRoute,
  ReferralsRoute: ReferralsRoute,
    RecurringIndexRoute: RecurringIndexRoute,
    RecurringIndexRoute,
  SearchRoute: SearchRoute,
  AdminVerificationRoute: AdminVerificationRoute,
  AdminScoresRoute: AdminScoresRoute,
  ArtisanIdRoute: ArtisanIdRoute,
  ArtisanEarningsRoute: ArtisanEarningsRoute,
  ArtisanReviewsRoute: ArtisanReviewsRoute,
  ArtisansJobsRoute: ArtisansJobsRouteWithChildren,
  JobsPostRoute: JobsPostRoute,
  JobsMineRoute: JobsMineRoute,
  BookingsBookingIdRoute: BookingsBookingIdRoute,
  JobsJobIdBidsRoute: JobsJobIdBidsRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  OnboardingArtisanRoute: OnboardingArtisanRoute,
  ProfilePortfolioRoute: ProfilePortfolioRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
