/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProRouteImport } from './routes/pro'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtisanIdRouteImport } from './routes/artisan.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisanIdRoute = ArtisanIdRouteImport.update({
  id: '/artisan/$id',
  path: '/artisan/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pro': typeof ProRoute
  '/search': typeof SearchRoute
  '/artisan/$id': typeof ArtisanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pro': typeof ProRoute
  '/search': typeof SearchRoute
  '/artisan/$id': typeof ArtisanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pro': typeof ProRoute
  '/search': typeof SearchRoute
  '/artisan/$id': typeof ArtisanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pro' | '/search' | '/artisan/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pro' | '/search' | '/artisan/$id'
  id: '__root__' | '/' | '/pro' | '/search' | '/artisan/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProRoute: typeof ProRoute
  SearchRoute: typeof SearchRoute
  ArtisanIdRoute: typeof ArtisanIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisan/$id': {
      id: '/artisan/$id'
      path: '/artisan/$id'
      fullPath: '/artisan/$id'
      preLoaderRoute: typeof ArtisanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProRoute: ProRoute,
  SearchRoute: SearchRoute,
  ArtisanIdRoute: ArtisanIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
